version: '3.8'

services:

  api-gateway:
    build: ./api-getway
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - user-service
      - auth-service
      - product-service
      - cart-service
    env_file:
      - ./api-getway/.env
    restart: always
    networks:
      - micro-net

  user-service:
    build: ./user
    env_file:
      - ./user/.env
    restart: always
    environment :
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - micro-net

  auth-service:
    build: ./auth
    env_file:
      - ./auth/.env
    restart: always
    environment :
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - micro-net
  product-service:
    build: ./product
    env_file:
      - ./product/.env
    restart: always
    environment :
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - micro-net

  cart-service:
    build: ./cart
    env_file:
      - ./cart/.env
    restart: always
    environment :
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - micro-net
  redis: 
    image: redis:alpine
    container_name: redis-pro
    ports:
      - "6379:6379"
    networks:
      - micro-net

networks:
  micro-net: