version: '3.8'

services:

  api-gateway:
    build:
      context: ./api-getway
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
      - product-service
    env_file:
      - ./api-getway/.env
    volumes:
      - ./api-getway:/app
    command: npm run start:dev
    environment :
      - REDIS_HOST=redis
    networks:
      - micro-net

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    env_file:
      - ./user/.env
    volumes:
      - ./user:/app
      - /app/node_modules
    command: npm run start:dev
    environment :
      - REDIS_HOST=redis
    networks:
      - micro-net



  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    env_file:
      - ./auth/.env
    volumes:
      - ./auth:/app
      - /app/node_modules
    command: npm run start:dev
    environment :
      - REDIS_HOST=redis
    networks:
      - micro-net

  product-service:
    build:
      context: ./product
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3000"
    env_file:
      - ./product/.env
    volumes:
      - ./product:/app
      - /app/node_modules
    command: npm run start:dev
    environment :
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - micro-net

  redis: 
    image: redis:alpine
    container_name: redis-dev
    ports:
      - "6379:6379"






networks:
  micro-net: